/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package Jflextest;
import static Jflextest.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>NewLexer.flex</tt>
 */
class NewLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\2\0\2\0\1\0\22\0\1\0\7\0\1\5\1\6\3\0"+
    "\1\4\1\3\1\0\1\2\1\13\1\13\1\13\1\14\1\12\4\2"+
    "\6\0\1\11\32\0\1\7\1\0\1\10\3\0\32\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\17\0\1\1\5\0\1\1\43\0\1\2\16\0\1\3"+
    "\5\0\1\4\1\0\1\2\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\15\0\32\0\47\0\64\0\101\0\116\0\133"+
    "\0\150\0\165\0\202\0\217\0\234\0\251\0\266\0\303"+
    "\0\320\0\335\0\352\0\367\0\u0104\0\150\0\u0111\0\u011e"+
    "\0\u012b\0\u0138\0\u0145\0\u0152\0\u015f\0\u016c\0\u0179\0\u0186"+
    "\0\u0193\0\u01a0\0\u01ad\0\u01ba\0\u01c7\0\u01d4\0\u01e1\0\u01ee"+
    "\0\u01fb\0\u0208\0\u0215\0\u0222\0\u022f\0\u023c\0\u0249\0\u0256"+
    "\0\u0263\0\u0270\0\u027d\0\u028a\0\u0297\0\u02a4\0\u02b1\0\u02be"+
    "\0\u02cb\0\u02d8\0\u02e5\0\u02f2\0\u02ff\0\u030c\0\u0319\0\u0326"+
    "\0\u0333\0\u0340\0\u034d\0\u035a\0\u0367\0\u0374\0\u0381\0\u038e"+
    "\0\u035a\0\u039b\0\u03a8\0\u03b5\0\u03c2\0\u03cf\0\u03b5\0\u03dc"+
    "\0\u03cf\0\u03dc";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\2\0\1\4\1\0\1\5\2\0"+
    "\1\6\1\3\1\7\1\0\1\2\1\0\1\10\5\0"+
    "\1\11\5\0\1\12\7\0\3\12\2\0\1\13\7\0"+
    "\3\13\2\0\1\14\7\0\3\14\2\0\1\12\7\0"+
    "\3\15\2\0\1\16\7\0\3\16\1\0\1\17\14\0"+
    "\1\20\15\0\1\12\1\0\1\21\5\0\3\12\2\0"+
    "\1\22\7\0\3\22\2\0\1\23\7\0\3\23\2\0"+
    "\1\24\1\0\1\21\5\0\3\24\2\0\1\25\1\0"+
    "\1\21\5\0\3\25\1\0\1\17\7\0\1\26\4\0"+
    "\1\20\1\0\1\11\13\0\1\27\7\0\3\27\2\0"+
    "\1\22\3\0\1\30\3\0\3\22\2\0\1\31\7\0"+
    "\3\31\2\0\1\32\1\0\1\21\5\0\3\32\2\0"+
    "\1\33\1\0\1\21\5\0\3\33\2\0\1\34\7\0"+
    "\3\34\4\0\1\35\12\0\1\31\5\0\1\36\1\0"+
    "\3\31\2\0\1\37\1\0\1\21\5\0\3\37\2\0"+
    "\1\40\1\0\1\21\5\0\3\40\2\0\1\34\1\0"+
    "\1\41\5\0\3\34\2\0\1\42\7\0\3\42\4\0"+
    "\1\43\12\0\1\44\1\0\1\21\5\0\3\44\2\0"+
    "\1\45\1\0\1\21\5\0\3\45\2\0\1\46\7\0"+
    "\3\46\2\0\1\47\7\0\3\47\2\0\1\50\7\0"+
    "\3\50\2\0\1\51\1\0\1\21\5\0\3\51\2\0"+
    "\1\52\1\0\1\21\5\0\3\52\2\0\1\53\7\0"+
    "\3\53\2\0\1\47\1\0\1\54\5\0\3\47\2\0"+
    "\1\55\7\0\3\55\2\0\1\56\1\0\1\21\5\0"+
    "\3\56\2\0\1\57\1\0\1\21\5\0\3\57\2\0"+
    "\1\53\1\0\1\60\5\0\3\53\2\0\1\61\7\0"+
    "\3\61\2\0\1\55\1\0\1\62\5\0\3\55\2\0"+
    "\1\63\1\0\1\21\5\0\3\63\2\0\1\64\1\0"+
    "\1\21\5\0\3\64\2\0\1\65\7\0\3\65\2\0"+
    "\1\66\7\0\3\66\2\0\1\67\7\0\3\67\2\0"+
    "\1\70\1\0\1\21\5\0\3\70\2\0\1\71\1\0"+
    "\1\21\5\0\3\71\2\0\1\72\7\0\3\72\2\0"+
    "\1\66\1\0\1\73\5\0\3\66\2\0\1\74\7\0"+
    "\3\74\2\0\1\75\1\0\1\21\5\0\3\75\2\0"+
    "\1\76\1\0\1\21\5\0\3\76\2\0\1\72\1\0"+
    "\1\77\5\0\3\72\2\0\1\100\7\0\3\100\2\0"+
    "\1\74\1\0\1\101\5\0\3\74\2\0\1\102\1\0"+
    "\1\21\5\0\3\102\2\0\1\103\1\0\1\21\5\0"+
    "\3\103\2\0\1\104\7\0\3\104\2\0\1\105\7\0"+
    "\3\105\2\0\1\106\7\0\3\106\2\0\1\107\1\0"+
    "\1\21\5\0\3\107\2\0\1\110\1\0\1\21\5\0"+
    "\3\110\2\0\1\111\7\0\3\111\2\0\1\105\1\0"+
    "\1\112\5\0\3\105\2\0\1\113\7\0\3\113\2\0"+
    "\1\114\1\0\1\21\5\0\3\114\2\0\1\115\1\0"+
    "\1\21\5\0\3\115\2\0\1\116\7\0\3\116\2\0"+
    "\1\113\1\0\1\77\5\0\3\113\2\0\1\117\1\0"+
    "\1\21\5\0\3\117\2\0\1\120\1\0\1\21\5\0"+
    "\3\120\2\0\1\121\7\0\3\121\2\0\1\122\1\0"+
    "\1\21\5\0\3\122";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1001];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\17\0\1\1\5\0\1\1\43\0\1\1\16\0\1\1"+
    "\5\0\1\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  NewLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  NewLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 58) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { lexeme=yytext(); return CORREO;
          }
        case 6: break;
        case 2: 
          { lexeme=yytext(); return TELOCAL;
          }
        case 7: break;
        case 3: 
          { lexeme=yytext(); return TELCEL;
          }
        case 8: break;
        case 4: 
          { lexeme=yytext(); return MASTERCARD;
          }
        case 9: break;
        case 5: 
          { lexeme=yytext(); return VISA;
          }
        case 10: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
